module great-sage/gateway

go 1.22

require (
	// gRPC Go client — calls Rust orchestrator at localhost:50051
	google.golang.org/grpc v1.65.0

	// Protocol Buffers Go runtime — required by grpc and generated code
	google.golang.org/protobuf v1.34.2

	// Request ID generation for tracing requests across services
	github.com/google/uuid v1.6.0

	// WebSocket server — streams model output tokens to browser in real time
	github.com/gorilla/websocket v1.5.3

	// Headless Chrome control for deep web research tasks (Part 9)
	github.com/chromedp/chromedp v0.10.0
)

// go.sum is generated by running: go mod tidy
// Run from services\gateway\ when implementing Part 9 (Network, Browser & Screen)
