# generate_proto.ps1
# Regenerates gRPC code for Go and Python from proto\tempest.proto.
#
# Run this script ONLY when tempest.proto changes.
# Rust code is generated automatically by build.rs on `cargo build` — no step needed here.
#
# Prerequisites (run once, part of §1 environment setup):
#   winget install protobuf                          # installs protoc
#   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
#   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
#   pip install grpcio-tools
#
# Usage:
#   cd "D:\Project LLM\great sage"
#   .\scripts\generate_proto.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Paths ────────────────────────────────────────────────────────────────────
$Root      = "D:\Project LLM\great sage"
$ProtoFile = "$Root\proto\tempest.proto"
$ProtoDir  = "$Root\proto"

# Go output — generated files land next to gateway service code
$GoOut     = "$Root\services\gateway\proto"

# Python output — generated files land next to inference service code
$PyOut     = "$Root\services\inference\proto"

# ── Validate proto exists ────────────────────────────────────────────────────
if (-not (Test-Path $ProtoFile)) {
    Write-Error "tempest.proto not found at: $ProtoFile"
    exit 1
}

# ── Create output directories if missing ────────────────────────────────────
New-Item -ItemType Directory -Force -Path $GoOut | Out-Null
New-Item -ItemType Directory -Force -Path $PyOut | Out-Null

Write-Host "Generating Go gRPC code..." -ForegroundColor Cyan

# protoc-gen-go        → generates message structs     (tempest.pb.go)
# protoc-gen-go-grpc   → generates service interfaces  (tempest_grpc.pb.go)
& protoc `
    --proto_path="$ProtoDir" `
    --go_out="$GoOut" `
    --go_opt=paths=source_relative `
    --go-grpc_out="$GoOut" `
    --go-grpc_opt=paths=source_relative `
    "$ProtoFile"

if ($LASTEXITCODE -ne 0) {
    Write-Error "protoc (Go) failed with exit code $LASTEXITCODE"
    exit 1
}
Write-Host "  → $GoOut\tempest.pb.go" -ForegroundColor Green
Write-Host "  → $GoOut\tempest_grpc.pb.go" -ForegroundColor Green

Write-Host ""
Write-Host "Generating Python gRPC code..." -ForegroundColor Cyan

# grpcio-tools.protoc  → generates message classes    (tempest_pb2.py)
#                      → generates service stubs       (tempest_pb2_grpc.py)
python -m grpc_tools.protoc `
    -I "$ProtoDir" `
    --python_out="$PyOut" `
    --grpc_python_out="$PyOut" `
    "$ProtoFile"

if ($LASTEXITCODE -ne 0) {
    Write-Error "grpc_tools.protoc (Python) failed with exit code $LASTEXITCODE"
    exit 1
}
Write-Host "  → $PyOut\tempest_pb2.py" -ForegroundColor Green
Write-Host "  → $PyOut\tempest_pb2_grpc.py" -ForegroundColor Green

Write-Host ""
Write-Host "Proto generation complete." -ForegroundColor Green
Write-Host "Rust code is auto-generated by build.rs on the next 'cargo build'." -ForegroundColor DarkGray
