# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tempest_pb2 as tempest__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tempest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GatewayToOrchestratorStub(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 1 — GatewayToOrchestrator
    Caller:   Go HTTP/WebSocket server  (services/gateway)       binds :8000/:8001
    Receiver: Rust Orchestrator         (services/orchestrator)  binds :50051
    Sections: §30 Session Lifecycle · §31 Intent Router · §32 Context Assembler
    §34 Audit Log · §39 HTTP/WS Server
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/tempest.GatewayToOrchestrator/StartSession',
                request_serializer=tempest__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=tempest__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_stream(
                '/tempest.GatewayToOrchestrator/SendMessage',
                request_serializer=tempest__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=tempest__pb2.TokenChunk.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/tempest.GatewayToOrchestrator/EndSession',
                request_serializer=tempest__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=tempest__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/tempest.GatewayToOrchestrator/GetSystemStatus',
                request_serializer=tempest__pb2.SystemStatusRequest.SerializeToString,
                response_deserializer=tempest__pb2.SystemStatusResponse.FromString,
                _registered_method=True)
        self.GetAuditLog = channel.unary_unary(
                '/tempest.GatewayToOrchestrator/GetAuditLog',
                request_serializer=tempest__pb2.AuditLogRequest.SerializeToString,
                response_deserializer=tempest__pb2.AuditLogResponse.FromString,
                _registered_method=True)
        self.NotifyFileAdded = channel.unary_unary(
                '/tempest.GatewayToOrchestrator/NotifyFileAdded',
                request_serializer=tempest__pb2.FileAddedRequest.SerializeToString,
                response_deserializer=tempest__pb2.FileAddedResponse.FromString,
                _registered_method=True)


class GatewayToOrchestratorServicer(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 1 — GatewayToOrchestrator
    Caller:   Go HTTP/WebSocket server  (services/gateway)       binds :8000/:8001
    Receiver: Rust Orchestrator         (services/orchestrator)  binds :50051
    Sections: §30 Session Lifecycle · §31 Intent Router · §32 Context Assembler
    §34 Audit Log · §39 HTTP/WS Server
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def StartSession(self, request, context):
        """User opens the app — Rust creates a session, loads memory, returns greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """User sends a message — Rust processes it and streams tokens back one by one
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """User closes the app — Rust saves summary, writes episodic memory, clears state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """Dashboard polls this every 5 seconds for VRAM, latency, chunk count, backup status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditLog(self, request, context):
        """Admin view of security events from the audit log (§34)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyFileAdded(self, request, context):
        """User drops a file into incoming\ — Go notifies Rust to queue it for ingestion (§10)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayToOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=tempest__pb2.StartSessionRequest.FromString,
                    response_serializer=tempest__pb2.StartSessionResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=tempest__pb2.SendMessageRequest.FromString,
                    response_serializer=tempest__pb2.TokenChunk.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=tempest__pb2.EndSessionRequest.FromString,
                    response_serializer=tempest__pb2.EndSessionResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=tempest__pb2.SystemStatusRequest.FromString,
                    response_serializer=tempest__pb2.SystemStatusResponse.SerializeToString,
            ),
            'GetAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLog,
                    request_deserializer=tempest__pb2.AuditLogRequest.FromString,
                    response_serializer=tempest__pb2.AuditLogResponse.SerializeToString,
            ),
            'NotifyFileAdded': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyFileAdded,
                    request_deserializer=tempest__pb2.FileAddedRequest.FromString,
                    response_serializer=tempest__pb2.FileAddedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tempest.GatewayToOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tempest.GatewayToOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayToOrchestrator(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 1 — GatewayToOrchestrator
    Caller:   Go HTTP/WebSocket server  (services/gateway)       binds :8000/:8001
    Receiver: Rust Orchestrator         (services/orchestrator)  binds :50051
    Sections: §30 Session Lifecycle · §31 Intent Router · §32 Context Assembler
    §34 Audit Log · §39 HTTP/WS Server
    ═══════════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.GatewayToOrchestrator/StartSession',
            tempest__pb2.StartSessionRequest.SerializeToString,
            tempest__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tempest.GatewayToOrchestrator/SendMessage',
            tempest__pb2.SendMessageRequest.SerializeToString,
            tempest__pb2.TokenChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.GatewayToOrchestrator/EndSession',
            tempest__pb2.EndSessionRequest.SerializeToString,
            tempest__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.GatewayToOrchestrator/GetSystemStatus',
            tempest__pb2.SystemStatusRequest.SerializeToString,
            tempest__pb2.SystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.GatewayToOrchestrator/GetAuditLog',
            tempest__pb2.AuditLogRequest.SerializeToString,
            tempest__pb2.AuditLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyFileAdded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.GatewayToOrchestrator/NotifyFileAdded',
            tempest__pb2.FileAddedRequest.SerializeToString,
            tempest__pb2.FileAddedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrchestratorToInferenceStub(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 2 — OrchestratorToInference
    Caller:   Rust Orchestrator         (services/orchestrator)
    Receiver: Python Inference Service  (services/inference)    binds :50052
    Sections: §5 Inference Service · §6 AWQ Quantization · §8 VRAM Manager
    §9 KV Cache · §15 Embeddings · §18 HyDE · §35 Vosk STT
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/tempest.OrchestratorToInference/Generate',
                request_serializer=tempest__pb2.GenerateRequest.SerializeToString,
                response_deserializer=tempest__pb2.GenerateChunk.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/tempest.OrchestratorToInference/Embed',
                request_serializer=tempest__pb2.EmbedRequest.SerializeToString,
                response_deserializer=tempest__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.EmbedBatch = channel.unary_unary(
                '/tempest.OrchestratorToInference/EmbedBatch',
                request_serializer=tempest__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=tempest__pb2.EmbedBatchResponse.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_unary(
                '/tempest.OrchestratorToInference/Transcribe',
                request_serializer=tempest__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=tempest__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/tempest.OrchestratorToInference/LoadModel',
                request_serializer=tempest__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=tempest__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/tempest.OrchestratorToInference/UnloadModel',
                request_serializer=tempest__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=tempest__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.GetVRAMStatus = channel.unary_unary(
                '/tempest.OrchestratorToInference/GetVRAMStatus',
                request_serializer=tempest__pb2.VRAMStatusRequest.SerializeToString,
                response_deserializer=tempest__pb2.VRAMStatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/tempest.OrchestratorToInference/HealthCheck',
                request_serializer=tempest__pb2.HealthRequest.SerializeToString,
                response_deserializer=tempest__pb2.HealthResponse.FromString,
                _registered_method=True)


class OrchestratorToInferenceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 2 — OrchestratorToInference
    Caller:   Rust Orchestrator         (services/orchestrator)
    Receiver: Python Inference Service  (services/inference)    binds :50052
    Sections: §5 Inference Service · §6 AWQ Quantization · §8 VRAM Manager
    §9 KV Cache · §15 Embeddings · §18 HyDE · §35 Vosk STT
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def Generate(self, request, context):
        """Send assembled 6-slot prompt, receive token stream (§32 Context Assembler builds the prompt)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Embed one text string into a 768-dim vector (used for HyDE query embedding §18)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """Embed a batch of strings — used by the bulk ingestion pipeline (§15)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Transcribe raw PCM audio bytes via Vosk STT (§35)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Load a model into VRAM — called by VRAM manager on mode switch (§8)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Free a model from VRAM before loading another — prevents OOM crashes (§8)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVRAMStatus(self, request, context):
        """Rust polls this every 10 seconds for the dashboard and VRAM budget enforcement (§8, §79)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Startup check — is GPU visible, model loaded, service alive?
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorToInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=tempest__pb2.GenerateRequest.FromString,
                    response_serializer=tempest__pb2.GenerateChunk.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=tempest__pb2.EmbedRequest.FromString,
                    response_serializer=tempest__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=tempest__pb2.EmbedBatchRequest.FromString,
                    response_serializer=tempest__pb2.EmbedBatchResponse.SerializeToString,
            ),
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=tempest__pb2.TranscribeRequest.FromString,
                    response_serializer=tempest__pb2.TranscribeResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=tempest__pb2.LoadModelRequest.FromString,
                    response_serializer=tempest__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=tempest__pb2.UnloadModelRequest.FromString,
                    response_serializer=tempest__pb2.UnloadModelResponse.SerializeToString,
            ),
            'GetVRAMStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVRAMStatus,
                    request_deserializer=tempest__pb2.VRAMStatusRequest.FromString,
                    response_serializer=tempest__pb2.VRAMStatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=tempest__pb2.HealthRequest.FromString,
                    response_serializer=tempest__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tempest.OrchestratorToInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tempest.OrchestratorToInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorToInference(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 2 — OrchestratorToInference
    Caller:   Rust Orchestrator         (services/orchestrator)
    Receiver: Python Inference Service  (services/inference)    binds :50052
    Sections: §5 Inference Service · §6 AWQ Quantization · §8 VRAM Manager
    §9 KV Cache · §15 Embeddings · §18 HyDE · §35 Vosk STT
    ═══════════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tempest.OrchestratorToInference/Generate',
            tempest__pb2.GenerateRequest.SerializeToString,
            tempest__pb2.GenerateChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToInference/Embed',
            tempest__pb2.EmbedRequest.SerializeToString,
            tempest__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToInference/EmbedBatch',
            tempest__pb2.EmbedBatchRequest.SerializeToString,
            tempest__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToInference/Transcribe',
            tempest__pb2.TranscribeRequest.SerializeToString,
            tempest__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToInference/LoadModel',
            tempest__pb2.LoadModelRequest.SerializeToString,
            tempest__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToInference/UnloadModel',
            tempest__pb2.UnloadModelRequest.SerializeToString,
            tempest__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVRAMStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToInference/GetVRAMStatus',
            tempest__pb2.VRAMStatusRequest.SerializeToString,
            tempest__pb2.VRAMStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToInference/HealthCheck',
            tempest__pb2.HealthRequest.SerializeToString,
            tempest__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrchestratorToVoiceStub(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 3 — OrchestratorToVoice
    Caller:   Rust Orchestrator
    Receiver: Python Voice Service  (part of services/inference or dedicated sub-service)
    Sections: §36 Wake Word · §37 Piper TTS · §38 Voice Mode FSM
    §42 Screen Capture · §43 Active Window Detection
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SynthesizeSentence = channel.unary_unary(
                '/tempest.OrchestratorToVoice/SynthesizeSentence',
                request_serializer=tempest__pb2.SynthRequest.SerializeToString,
                response_deserializer=tempest__pb2.SynthResponse.FromString,
                _registered_method=True)
        self.StreamWakeWord = channel.unary_stream(
                '/tempest.OrchestratorToVoice/StreamWakeWord',
                request_serializer=tempest__pb2.WakeWordStartReq.SerializeToString,
                response_deserializer=tempest__pb2.WakeWordEvent.FromString,
                _registered_method=True)
        self.SetVoiceMode = channel.unary_unary(
                '/tempest.OrchestratorToVoice/SetVoiceMode',
                request_serializer=tempest__pb2.VoiceModeRequest.SerializeToString,
                response_deserializer=tempest__pb2.VoiceModeResponse.FromString,
                _registered_method=True)
        self.CaptureScreen = channel.unary_unary(
                '/tempest.OrchestratorToVoice/CaptureScreen',
                request_serializer=tempest__pb2.CaptureRequest.SerializeToString,
                response_deserializer=tempest__pb2.CaptureResponse.FromString,
                _registered_method=True)
        self.GetActiveWindow = channel.unary_unary(
                '/tempest.OrchestratorToVoice/GetActiveWindow',
                request_serializer=tempest__pb2.WindowRequest.SerializeToString,
                response_deserializer=tempest__pb2.WindowResponse.FromString,
                _registered_method=True)


class OrchestratorToVoiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 3 — OrchestratorToVoice
    Caller:   Rust Orchestrator
    Receiver: Python Voice Service  (part of services/inference or dedicated sub-service)
    Sections: §36 Wake Word · §37 Piper TTS · §38 Voice Mode FSM
    §42 Screen Capture · §43 Active Window Detection
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def SynthesizeSentence(self, request, context):
        """Send one sentence of text — receive WAV bytes for immediate audio playback (§37 Piper TTS)
        Called once per sentence as Rust detects sentence boundaries in the token stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWakeWord(self, request, context):
        """Rust opens this stream at startup — Python pushes an event each time wake word is detected (§36)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVoiceMode(self, request, context):
        """Notify voice service of mode change so it can adjust TTS style and VAD sensitivity (§38)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureScreen(self, request, context):
        """Capture the active window as PNG, run OCR, return the extracted text (§42)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveWindow(self, request, context):
        """Return the current foreground window title and its inferred context tag (§43)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorToVoiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SynthesizeSentence': grpc.unary_unary_rpc_method_handler(
                    servicer.SynthesizeSentence,
                    request_deserializer=tempest__pb2.SynthRequest.FromString,
                    response_serializer=tempest__pb2.SynthResponse.SerializeToString,
            ),
            'StreamWakeWord': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWakeWord,
                    request_deserializer=tempest__pb2.WakeWordStartReq.FromString,
                    response_serializer=tempest__pb2.WakeWordEvent.SerializeToString,
            ),
            'SetVoiceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVoiceMode,
                    request_deserializer=tempest__pb2.VoiceModeRequest.FromString,
                    response_serializer=tempest__pb2.VoiceModeResponse.SerializeToString,
            ),
            'CaptureScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureScreen,
                    request_deserializer=tempest__pb2.CaptureRequest.FromString,
                    response_serializer=tempest__pb2.CaptureResponse.SerializeToString,
            ),
            'GetActiveWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveWindow,
                    request_deserializer=tempest__pb2.WindowRequest.FromString,
                    response_serializer=tempest__pb2.WindowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tempest.OrchestratorToVoice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tempest.OrchestratorToVoice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorToVoice(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 3 — OrchestratorToVoice
    Caller:   Rust Orchestrator
    Receiver: Python Voice Service  (part of services/inference or dedicated sub-service)
    Sections: §36 Wake Word · §37 Piper TTS · §38 Voice Mode FSM
    §42 Screen Capture · §43 Active Window Detection
    ═══════════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def SynthesizeSentence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToVoice/SynthesizeSentence',
            tempest__pb2.SynthRequest.SerializeToString,
            tempest__pb2.SynthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWakeWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tempest.OrchestratorToVoice/StreamWakeWord',
            tempest__pb2.WakeWordStartReq.SerializeToString,
            tempest__pb2.WakeWordEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVoiceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToVoice/SetVoiceMode',
            tempest__pb2.VoiceModeRequest.SerializeToString,
            tempest__pb2.VoiceModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToVoice/CaptureScreen',
            tempest__pb2.CaptureRequest.SerializeToString,
            tempest__pb2.CaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToVoice/GetActiveWindow',
            tempest__pb2.WindowRequest.SerializeToString,
            tempest__pb2.WindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrchestratorToToolsStub(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 4 — OrchestratorToTools
    Caller:   Rust Orchestrator (agentic loop dispatcher in §45)
    Receiver: Python Tools Service  (services/tools — shares inference container or dedicated)
    Sections: §44 Tool Registry · §45 Agentic Loop · §46 Task Planner · §47 Research Agent
    §48 Result Injection · §49–§51 Claude API · §52–§55 Visual Output
    §56–§60 Active Learning
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchKnowledge = channel.unary_unary(
                '/tempest.OrchestratorToTools/SearchKnowledge',
                request_serializer=tempest__pb2.SearchKnowledgeReq.SerializeToString,
                response_deserializer=tempest__pb2.SearchKnowledgeRes.FromString,
                _registered_method=True)
        self.SaveToKnowledge = channel.unary_unary(
                '/tempest.OrchestratorToTools/SaveToKnowledge',
                request_serializer=tempest__pb2.SaveKnowledgeReq.SerializeToString,
                response_deserializer=tempest__pb2.SaveKnowledgeRes.FromString,
                _registered_method=True)
        self.BrowseWeb = channel.unary_unary(
                '/tempest.OrchestratorToTools/BrowseWeb',
                request_serializer=tempest__pb2.BrowseWebReq.SerializeToString,
                response_deserializer=tempest__pb2.BrowseWebRes.FromString,
                _registered_method=True)
        self.DeepBrowse = channel.unary_unary(
                '/tempest.OrchestratorToTools/DeepBrowse',
                request_serializer=tempest__pb2.DeepBrowseReq.SerializeToString,
                response_deserializer=tempest__pb2.DeepBrowseRes.FromString,
                _registered_method=True)
        self.TakeScreenshot = channel.unary_unary(
                '/tempest.OrchestratorToTools/TakeScreenshot',
                request_serializer=tempest__pb2.ScreenshotReq.SerializeToString,
                response_deserializer=tempest__pb2.ScreenshotRes.FromString,
                _registered_method=True)
        self.ReadScreen = channel.unary_unary(
                '/tempest.OrchestratorToTools/ReadScreen',
                request_serializer=tempest__pb2.ReadScreenReq.SerializeToString,
                response_deserializer=tempest__pb2.ReadScreenRes.FromString,
                _registered_method=True)
        self.CallClaude = channel.unary_unary(
                '/tempest.OrchestratorToTools/CallClaude',
                request_serializer=tempest__pb2.CallClaudeReq.SerializeToString,
                response_deserializer=tempest__pb2.CallClaudeRes.FromString,
                _registered_method=True)
        self.GenerateFlashcard = channel.unary_unary(
                '/tempest.OrchestratorToTools/GenerateFlashcard',
                request_serializer=tempest__pb2.FlashcardReq.SerializeToString,
                response_deserializer=tempest__pb2.FlashcardRes.FromString,
                _registered_method=True)
        self.GenerateDiagram = channel.unary_unary(
                '/tempest.OrchestratorToTools/GenerateDiagram',
                request_serializer=tempest__pb2.DiagramReq.SerializeToString,
                response_deserializer=tempest__pb2.DiagramRes.FromString,
                _registered_method=True)
        self.GenerateMindMap = channel.unary_unary(
                '/tempest.OrchestratorToTools/GenerateMindMap',
                request_serializer=tempest__pb2.MindMapReq.SerializeToString,
                response_deserializer=tempest__pb2.MindMapRes.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/tempest.OrchestratorToTools/GenerateReport',
                request_serializer=tempest__pb2.ReportReq.SerializeToString,
                response_deserializer=tempest__pb2.ReportRes.FromString,
                _registered_method=True)
        self.CreateQuiz = channel.unary_unary(
                '/tempest.OrchestratorToTools/CreateQuiz',
                request_serializer=tempest__pb2.QuizReq.SerializeToString,
                response_deserializer=tempest__pb2.QuizRes.FromString,
                _registered_method=True)
        self.RunCalculation = channel.unary_unary(
                '/tempest.OrchestratorToTools/RunCalculation',
                request_serializer=tempest__pb2.CalcReq.SerializeToString,
                response_deserializer=tempest__pb2.CalcRes.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/tempest.OrchestratorToTools/ReadFile',
                request_serializer=tempest__pb2.ReadFileReq.SerializeToString,
                response_deserializer=tempest__pb2.ReadFileRes.FromString,
                _registered_method=True)
        self.TriggerAutoFill = channel.unary_unary(
                '/tempest.OrchestratorToTools/TriggerAutoFill',
                request_serializer=tempest__pb2.AutoFillReq.SerializeToString,
                response_deserializer=tempest__pb2.AutoFillRes.FromString,
                _registered_method=True)


class OrchestratorToToolsServicer(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 4 — OrchestratorToTools
    Caller:   Rust Orchestrator (agentic loop dispatcher in §45)
    Receiver: Python Tools Service  (services/tools — shares inference container or dedicated)
    Sections: §44 Tool Registry · §45 Agentic Loop · §46 Task Planner · §47 Research Agent
    §48 Result Injection · §49–§51 Claude API · §52–§55 Visual Output
    §56–§60 Active Learning
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def SearchKnowledge(self, request, context):
        """── Knowledge tools ────────────────────────────────────────────────────────

        Search FAISS + knowledge graph for relevant chunks (§16, §19 re-ranking)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveToKnowledge(self, request, context):
        """Save new content to the knowledge ingestion pipeline (§51, §58)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowseWeb(self, request, context):
        """── Web tools ──────────────────────────────────────────────────────────────

        Simple HTTP GET via whitelist fetcher (§40) — returns page text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeepBrowse(self, request, context):
        """Full Playwright browser action — click, fill, extract, screenshot (§41)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeScreenshot(self, request, context):
        """── Screen tools ───────────────────────────────────────────────────────────

        Capture screenshot — delegates to Voice service CaptureScreen (§42)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadScreen(self, request, context):
        """Capture screen and return OCR text as a tool result (§42)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallClaude(self, request, context):
        """── Claude API tool ────────────────────────────────────────────────────────

        Call Claude API with a structured prompt template (§50)
        Used by: gap fill (§49), research agent (§47), training data gen (§68)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFlashcard(self, request, context):
        """── Visual output tools ────────────────────────────────────────────────────

        Generate PNG flashcard images via Pillow (§52)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDiagram(self, request, context):
        """Render Mermaid diagram to PNG via Mermaid CLI (§53)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateMindMap(self, request, context):
        """Build interactive mind map HTML + static PNG from knowledge graph (§54)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Generate PDF/HTML study report via reportlab + matplotlib (§55)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateQuiz(self, request, context):
        """── Teaching tools ─────────────────────────────────────────────────────────

        Generate MCQ quiz questions with per-option explanations (§62)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCalculation(self, request, context):
        """── Utility tools ──────────────────────────────────────────────────────────

        Evaluate a mathematical or logical expression (§44)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Read a file — restricted to output\ and incoming\ only (§75 permission system)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerAutoFill(self, request, context):
        """── Active learning ────────────────────────────────────────────────────────

        Trigger the auto-fill pipeline for a specific topic (§58)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorToToolsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=tempest__pb2.SearchKnowledgeReq.FromString,
                    response_serializer=tempest__pb2.SearchKnowledgeRes.SerializeToString,
            ),
            'SaveToKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveToKnowledge,
                    request_deserializer=tempest__pb2.SaveKnowledgeReq.FromString,
                    response_serializer=tempest__pb2.SaveKnowledgeRes.SerializeToString,
            ),
            'BrowseWeb': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowseWeb,
                    request_deserializer=tempest__pb2.BrowseWebReq.FromString,
                    response_serializer=tempest__pb2.BrowseWebRes.SerializeToString,
            ),
            'DeepBrowse': grpc.unary_unary_rpc_method_handler(
                    servicer.DeepBrowse,
                    request_deserializer=tempest__pb2.DeepBrowseReq.FromString,
                    response_serializer=tempest__pb2.DeepBrowseRes.SerializeToString,
            ),
            'TakeScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeScreenshot,
                    request_deserializer=tempest__pb2.ScreenshotReq.FromString,
                    response_serializer=tempest__pb2.ScreenshotRes.SerializeToString,
            ),
            'ReadScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadScreen,
                    request_deserializer=tempest__pb2.ReadScreenReq.FromString,
                    response_serializer=tempest__pb2.ReadScreenRes.SerializeToString,
            ),
            'CallClaude': grpc.unary_unary_rpc_method_handler(
                    servicer.CallClaude,
                    request_deserializer=tempest__pb2.CallClaudeReq.FromString,
                    response_serializer=tempest__pb2.CallClaudeRes.SerializeToString,
            ),
            'GenerateFlashcard': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFlashcard,
                    request_deserializer=tempest__pb2.FlashcardReq.FromString,
                    response_serializer=tempest__pb2.FlashcardRes.SerializeToString,
            ),
            'GenerateDiagram': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDiagram,
                    request_deserializer=tempest__pb2.DiagramReq.FromString,
                    response_serializer=tempest__pb2.DiagramRes.SerializeToString,
            ),
            'GenerateMindMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateMindMap,
                    request_deserializer=tempest__pb2.MindMapReq.FromString,
                    response_serializer=tempest__pb2.MindMapRes.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=tempest__pb2.ReportReq.FromString,
                    response_serializer=tempest__pb2.ReportRes.SerializeToString,
            ),
            'CreateQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQuiz,
                    request_deserializer=tempest__pb2.QuizReq.FromString,
                    response_serializer=tempest__pb2.QuizRes.SerializeToString,
            ),
            'RunCalculation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCalculation,
                    request_deserializer=tempest__pb2.CalcReq.FromString,
                    response_serializer=tempest__pb2.CalcRes.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=tempest__pb2.ReadFileReq.FromString,
                    response_serializer=tempest__pb2.ReadFileRes.SerializeToString,
            ),
            'TriggerAutoFill': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerAutoFill,
                    request_deserializer=tempest__pb2.AutoFillReq.FromString,
                    response_serializer=tempest__pb2.AutoFillRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tempest.OrchestratorToTools', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tempest.OrchestratorToTools', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorToTools(object):
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE 4 — OrchestratorToTools
    Caller:   Rust Orchestrator (agentic loop dispatcher in §45)
    Receiver: Python Tools Service  (services/tools — shares inference container or dedicated)
    Sections: §44 Tool Registry · §45 Agentic Loop · §46 Task Planner · §47 Research Agent
    §48 Result Injection · §49–§51 Claude API · §52–§55 Visual Output
    §56–§60 Active Learning
    ═══════════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/SearchKnowledge',
            tempest__pb2.SearchKnowledgeReq.SerializeToString,
            tempest__pb2.SearchKnowledgeRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveToKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/SaveToKnowledge',
            tempest__pb2.SaveKnowledgeReq.SerializeToString,
            tempest__pb2.SaveKnowledgeRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowseWeb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/BrowseWeb',
            tempest__pb2.BrowseWebReq.SerializeToString,
            tempest__pb2.BrowseWebRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeepBrowse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/DeepBrowse',
            tempest__pb2.DeepBrowseReq.SerializeToString,
            tempest__pb2.DeepBrowseRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/TakeScreenshot',
            tempest__pb2.ScreenshotReq.SerializeToString,
            tempest__pb2.ScreenshotRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/ReadScreen',
            tempest__pb2.ReadScreenReq.SerializeToString,
            tempest__pb2.ReadScreenRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallClaude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/CallClaude',
            tempest__pb2.CallClaudeReq.SerializeToString,
            tempest__pb2.CallClaudeRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateFlashcard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/GenerateFlashcard',
            tempest__pb2.FlashcardReq.SerializeToString,
            tempest__pb2.FlashcardRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDiagram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/GenerateDiagram',
            tempest__pb2.DiagramReq.SerializeToString,
            tempest__pb2.DiagramRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateMindMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/GenerateMindMap',
            tempest__pb2.MindMapReq.SerializeToString,
            tempest__pb2.MindMapRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/GenerateReport',
            tempest__pb2.ReportReq.SerializeToString,
            tempest__pb2.ReportRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/CreateQuiz',
            tempest__pb2.QuizReq.SerializeToString,
            tempest__pb2.QuizRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCalculation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/RunCalculation',
            tempest__pb2.CalcReq.SerializeToString,
            tempest__pb2.CalcRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/ReadFile',
            tempest__pb2.ReadFileReq.SerializeToString,
            tempest__pb2.ReadFileRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerAutoFill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempest.OrchestratorToTools/TriggerAutoFill',
            tempest__pb2.AutoFillReq.SerializeToString,
            tempest__pb2.AutoFillRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
