// tempest.proto — Great Sage / Tempest gRPC Contract
// Single source of truth for all inter-service communication.
// If a method is not in this file, it does not exist.
//
// VERSIONING RULES — READ BEFORE EDITING
//
//   SAFE (backward compatible):
//     ✓ Add a new rpc method to an existing service
//     ✓ Add a new message type
//     ✓ Add a new field to an existing message (assign a NEW field number)
//     ✓ Add a new service block
//
//   NOT SAFE (breaks existing callers):
//     ✗ Remove or rename an existing rpc method
//     ✗ Remove or rename an existing message field
//     ✗ Change a field's type
//     ✗ Reuse a field number that was previously used (even if deleted)
//
//   When you add a new method:
//     1. Add it to tempest.proto
//     2. Run scripts\generate_proto.ps1
//     3. cargo build  (Rust regenerates automatically via build.rs)
//     4. Implement the handler in the receiver service
//     5. The caller can now use it — all without touching existing methods
//
// After editing: run scripts\generate_proto.ps1 and cargo build
// Ports: 50051 (Rust Orchestrator) · 50052 (Python Inference) — see config\grpc_ports.toml

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: tempest.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayToOrchestrator_StartSession_FullMethodName    = "/tempest.GatewayToOrchestrator/StartSession"
	GatewayToOrchestrator_SendMessage_FullMethodName     = "/tempest.GatewayToOrchestrator/SendMessage"
	GatewayToOrchestrator_EndSession_FullMethodName      = "/tempest.GatewayToOrchestrator/EndSession"
	GatewayToOrchestrator_GetSystemStatus_FullMethodName = "/tempest.GatewayToOrchestrator/GetSystemStatus"
	GatewayToOrchestrator_GetAuditLog_FullMethodName     = "/tempest.GatewayToOrchestrator/GetAuditLog"
	GatewayToOrchestrator_NotifyFileAdded_FullMethodName = "/tempest.GatewayToOrchestrator/NotifyFileAdded"
)

// GatewayToOrchestratorClient is the client API for GatewayToOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayToOrchestratorClient interface {
	// User opens the app — Rust creates a session, loads memory, returns greeting
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// User sends a message — Rust processes it and streams tokens back one by one
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenChunk], error)
	// User closes the app — Rust saves summary, writes episodic memory, clears state
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	// Dashboard polls this every 5 seconds for VRAM, latency, chunk count, backup status
	GetSystemStatus(ctx context.Context, in *SystemStatusRequest, opts ...grpc.CallOption) (*SystemStatusResponse, error)
	// Admin view of security events from the audit log (§34)
	GetAuditLog(ctx context.Context, in *AuditLogRequest, opts ...grpc.CallOption) (*AuditLogResponse, error)
	// User drops a file into incoming\ — Go notifies Rust to queue it for ingestion (§10)
	NotifyFileAdded(ctx context.Context, in *FileAddedRequest, opts ...grpc.CallOption) (*FileAddedResponse, error)
}

type gatewayToOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayToOrchestratorClient(cc grpc.ClientConnInterface) GatewayToOrchestratorClient {
	return &gatewayToOrchestratorClient{cc}
}

func (c *gatewayToOrchestratorClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, GatewayToOrchestrator_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayToOrchestratorClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayToOrchestrator_ServiceDesc.Streams[0], GatewayToOrchestrator_SendMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, TokenChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayToOrchestrator_SendMessageClient = grpc.ServerStreamingClient[TokenChunk]

func (c *gatewayToOrchestratorClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, GatewayToOrchestrator_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayToOrchestratorClient) GetSystemStatus(ctx context.Context, in *SystemStatusRequest, opts ...grpc.CallOption) (*SystemStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatusResponse)
	err := c.cc.Invoke(ctx, GatewayToOrchestrator_GetSystemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayToOrchestratorClient) GetAuditLog(ctx context.Context, in *AuditLogRequest, opts ...grpc.CallOption) (*AuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditLogResponse)
	err := c.cc.Invoke(ctx, GatewayToOrchestrator_GetAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayToOrchestratorClient) NotifyFileAdded(ctx context.Context, in *FileAddedRequest, opts ...grpc.CallOption) (*FileAddedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileAddedResponse)
	err := c.cc.Invoke(ctx, GatewayToOrchestrator_NotifyFileAdded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayToOrchestratorServer is the server API for GatewayToOrchestrator service.
// All implementations must embed UnimplementedGatewayToOrchestratorServer
// for forward compatibility.
type GatewayToOrchestratorServer interface {
	// User opens the app — Rust creates a session, loads memory, returns greeting
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// User sends a message — Rust processes it and streams tokens back one by one
	SendMessage(*SendMessageRequest, grpc.ServerStreamingServer[TokenChunk]) error
	// User closes the app — Rust saves summary, writes episodic memory, clears state
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	// Dashboard polls this every 5 seconds for VRAM, latency, chunk count, backup status
	GetSystemStatus(context.Context, *SystemStatusRequest) (*SystemStatusResponse, error)
	// Admin view of security events from the audit log (§34)
	GetAuditLog(context.Context, *AuditLogRequest) (*AuditLogResponse, error)
	// User drops a file into incoming\ — Go notifies Rust to queue it for ingestion (§10)
	NotifyFileAdded(context.Context, *FileAddedRequest) (*FileAddedResponse, error)
	mustEmbedUnimplementedGatewayToOrchestratorServer()
}

// UnimplementedGatewayToOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayToOrchestratorServer struct{}

func (UnimplementedGatewayToOrchestratorServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedGatewayToOrchestratorServer) SendMessage(*SendMessageRequest, grpc.ServerStreamingServer[TokenChunk]) error {
	return status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedGatewayToOrchestratorServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedGatewayToOrchestratorServer) GetSystemStatus(context.Context, *SystemStatusRequest) (*SystemStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStatus not implemented")
}
func (UnimplementedGatewayToOrchestratorServer) GetAuditLog(context.Context, *AuditLogRequest) (*AuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditLog not implemented")
}
func (UnimplementedGatewayToOrchestratorServer) NotifyFileAdded(context.Context, *FileAddedRequest) (*FileAddedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyFileAdded not implemented")
}
func (UnimplementedGatewayToOrchestratorServer) mustEmbedUnimplementedGatewayToOrchestratorServer() {}
func (UnimplementedGatewayToOrchestratorServer) testEmbeddedByValue()                               {}

// UnsafeGatewayToOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayToOrchestratorServer will
// result in compilation errors.
type UnsafeGatewayToOrchestratorServer interface {
	mustEmbedUnimplementedGatewayToOrchestratorServer()
}

func RegisterGatewayToOrchestratorServer(s grpc.ServiceRegistrar, srv GatewayToOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedGatewayToOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayToOrchestrator_ServiceDesc, srv)
}

func _GatewayToOrchestrator_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayToOrchestratorServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayToOrchestrator_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayToOrchestratorServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayToOrchestrator_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayToOrchestratorServer).SendMessage(m, &grpc.GenericServerStream[SendMessageRequest, TokenChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayToOrchestrator_SendMessageServer = grpc.ServerStreamingServer[TokenChunk]

func _GatewayToOrchestrator_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayToOrchestratorServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayToOrchestrator_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayToOrchestratorServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayToOrchestrator_GetSystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayToOrchestratorServer).GetSystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayToOrchestrator_GetSystemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayToOrchestratorServer).GetSystemStatus(ctx, req.(*SystemStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayToOrchestrator_GetAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayToOrchestratorServer).GetAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayToOrchestrator_GetAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayToOrchestratorServer).GetAuditLog(ctx, req.(*AuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayToOrchestrator_NotifyFileAdded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileAddedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayToOrchestratorServer).NotifyFileAdded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayToOrchestrator_NotifyFileAdded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayToOrchestratorServer).NotifyFileAdded(ctx, req.(*FileAddedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayToOrchestrator_ServiceDesc is the grpc.ServiceDesc for GatewayToOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayToOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tempest.GatewayToOrchestrator",
	HandlerType: (*GatewayToOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _GatewayToOrchestrator_StartSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _GatewayToOrchestrator_EndSession_Handler,
		},
		{
			MethodName: "GetSystemStatus",
			Handler:    _GatewayToOrchestrator_GetSystemStatus_Handler,
		},
		{
			MethodName: "GetAuditLog",
			Handler:    _GatewayToOrchestrator_GetAuditLog_Handler,
		},
		{
			MethodName: "NotifyFileAdded",
			Handler:    _GatewayToOrchestrator_NotifyFileAdded_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessage",
			Handler:       _GatewayToOrchestrator_SendMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tempest.proto",
}

const (
	OrchestratorToInference_Generate_FullMethodName      = "/tempest.OrchestratorToInference/Generate"
	OrchestratorToInference_Embed_FullMethodName         = "/tempest.OrchestratorToInference/Embed"
	OrchestratorToInference_EmbedBatch_FullMethodName    = "/tempest.OrchestratorToInference/EmbedBatch"
	OrchestratorToInference_Transcribe_FullMethodName    = "/tempest.OrchestratorToInference/Transcribe"
	OrchestratorToInference_LoadModel_FullMethodName     = "/tempest.OrchestratorToInference/LoadModel"
	OrchestratorToInference_UnloadModel_FullMethodName   = "/tempest.OrchestratorToInference/UnloadModel"
	OrchestratorToInference_GetVRAMStatus_FullMethodName = "/tempest.OrchestratorToInference/GetVRAMStatus"
	OrchestratorToInference_HealthCheck_FullMethodName   = "/tempest.OrchestratorToInference/HealthCheck"
)

// OrchestratorToInferenceClient is the client API for OrchestratorToInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorToInferenceClient interface {
	// Send assembled 6-slot prompt, receive token stream (§32 Context Assembler builds the prompt)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChunk], error)
	// Embed one text string into a 768-dim vector (used for HyDE query embedding §18)
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// Embed a batch of strings — used by the bulk ingestion pipeline (§15)
	EmbedBatch(ctx context.Context, in *EmbedBatchRequest, opts ...grpc.CallOption) (*EmbedBatchResponse, error)
	// Transcribe raw PCM audio bytes via Vosk STT (§35)
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
	// Load a model into VRAM — called by VRAM manager on mode switch (§8)
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	// Free a model from VRAM before loading another — prevents OOM crashes (§8)
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	// Rust polls this every 10 seconds for the dashboard and VRAM budget enforcement (§8, §79)
	GetVRAMStatus(ctx context.Context, in *VRAMStatusRequest, opts ...grpc.CallOption) (*VRAMStatusResponse, error)
	// Startup check — is GPU visible, model loaded, service alive?
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type orchestratorToInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorToInferenceClient(cc grpc.ClientConnInterface) OrchestratorToInferenceClient {
	return &orchestratorToInferenceClient{cc}
}

func (c *orchestratorToInferenceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorToInference_ServiceDesc.Streams[0], OrchestratorToInference_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorToInference_GenerateClient = grpc.ServerStreamingClient[GenerateChunk]

func (c *orchestratorToInferenceClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, OrchestratorToInference_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToInferenceClient) EmbedBatch(ctx context.Context, in *EmbedBatchRequest, opts ...grpc.CallOption) (*EmbedBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedBatchResponse)
	err := c.cc.Invoke(ctx, OrchestratorToInference_EmbedBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToInferenceClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, OrchestratorToInference_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToInferenceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, OrchestratorToInference_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToInferenceClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, OrchestratorToInference_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToInferenceClient) GetVRAMStatus(ctx context.Context, in *VRAMStatusRequest, opts ...grpc.CallOption) (*VRAMStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VRAMStatusResponse)
	err := c.cc.Invoke(ctx, OrchestratorToInference_GetVRAMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToInferenceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, OrchestratorToInference_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorToInferenceServer is the server API for OrchestratorToInference service.
// All implementations must embed UnimplementedOrchestratorToInferenceServer
// for forward compatibility.
type OrchestratorToInferenceServer interface {
	// Send assembled 6-slot prompt, receive token stream (§32 Context Assembler builds the prompt)
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateChunk]) error
	// Embed one text string into a 768-dim vector (used for HyDE query embedding §18)
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// Embed a batch of strings — used by the bulk ingestion pipeline (§15)
	EmbedBatch(context.Context, *EmbedBatchRequest) (*EmbedBatchResponse, error)
	// Transcribe raw PCM audio bytes via Vosk STT (§35)
	Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error)
	// Load a model into VRAM — called by VRAM manager on mode switch (§8)
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	// Free a model from VRAM before loading another — prevents OOM crashes (§8)
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	// Rust polls this every 10 seconds for the dashboard and VRAM budget enforcement (§8, §79)
	GetVRAMStatus(context.Context, *VRAMStatusRequest) (*VRAMStatusResponse, error)
	// Startup check — is GPU visible, model loaded, service alive?
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedOrchestratorToInferenceServer()
}

// UnimplementedOrchestratorToInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorToInferenceServer struct{}

func (UnimplementedOrchestratorToInferenceServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateChunk]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedOrchestratorToInferenceServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedOrchestratorToInferenceServer) EmbedBatch(context.Context, *EmbedBatchRequest) (*EmbedBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmbedBatch not implemented")
}
func (UnimplementedOrchestratorToInferenceServer) Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedOrchestratorToInferenceServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedOrchestratorToInferenceServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedOrchestratorToInferenceServer) GetVRAMStatus(context.Context, *VRAMStatusRequest) (*VRAMStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVRAMStatus not implemented")
}
func (UnimplementedOrchestratorToInferenceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOrchestratorToInferenceServer) mustEmbedUnimplementedOrchestratorToInferenceServer() {
}
func (UnimplementedOrchestratorToInferenceServer) testEmbeddedByValue() {}

// UnsafeOrchestratorToInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorToInferenceServer will
// result in compilation errors.
type UnsafeOrchestratorToInferenceServer interface {
	mustEmbedUnimplementedOrchestratorToInferenceServer()
}

func RegisterOrchestratorToInferenceServer(s grpc.ServiceRegistrar, srv OrchestratorToInferenceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorToInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorToInference_ServiceDesc, srv)
}

func _OrchestratorToInference_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorToInferenceServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorToInference_GenerateServer = grpc.ServerStreamingServer[GenerateChunk]

func _OrchestratorToInference_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToInferenceServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToInference_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToInferenceServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToInference_EmbedBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToInferenceServer).EmbedBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToInference_EmbedBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToInferenceServer).EmbedBatch(ctx, req.(*EmbedBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToInference_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToInferenceServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToInference_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToInferenceServer).Transcribe(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToInference_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToInferenceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToInference_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToInferenceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToInference_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToInferenceServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToInference_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToInferenceServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToInference_GetVRAMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VRAMStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToInferenceServer).GetVRAMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToInference_GetVRAMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToInferenceServer).GetVRAMStatus(ctx, req.(*VRAMStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToInference_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToInferenceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToInference_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToInferenceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorToInference_ServiceDesc is the grpc.ServiceDesc for OrchestratorToInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorToInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tempest.OrchestratorToInference",
	HandlerType: (*OrchestratorToInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _OrchestratorToInference_Embed_Handler,
		},
		{
			MethodName: "EmbedBatch",
			Handler:    _OrchestratorToInference_EmbedBatch_Handler,
		},
		{
			MethodName: "Transcribe",
			Handler:    _OrchestratorToInference_Transcribe_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _OrchestratorToInference_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _OrchestratorToInference_UnloadModel_Handler,
		},
		{
			MethodName: "GetVRAMStatus",
			Handler:    _OrchestratorToInference_GetVRAMStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OrchestratorToInference_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _OrchestratorToInference_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tempest.proto",
}

const (
	OrchestratorToVoice_SynthesizeSentence_FullMethodName = "/tempest.OrchestratorToVoice/SynthesizeSentence"
	OrchestratorToVoice_StreamWakeWord_FullMethodName     = "/tempest.OrchestratorToVoice/StreamWakeWord"
	OrchestratorToVoice_SetVoiceMode_FullMethodName       = "/tempest.OrchestratorToVoice/SetVoiceMode"
	OrchestratorToVoice_CaptureScreen_FullMethodName      = "/tempest.OrchestratorToVoice/CaptureScreen"
	OrchestratorToVoice_GetActiveWindow_FullMethodName    = "/tempest.OrchestratorToVoice/GetActiveWindow"
)

// OrchestratorToVoiceClient is the client API for OrchestratorToVoice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorToVoiceClient interface {
	// Send one sentence of text — receive WAV bytes for immediate audio playback (§37 Piper TTS)
	// Called once per sentence as Rust detects sentence boundaries in the token stream
	SynthesizeSentence(ctx context.Context, in *SynthRequest, opts ...grpc.CallOption) (*SynthResponse, error)
	// Rust opens this stream at startup — Python pushes an event each time wake word is detected (§36)
	StreamWakeWord(ctx context.Context, in *WakeWordStartReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WakeWordEvent], error)
	// Notify voice service of mode change so it can adjust TTS style and VAD sensitivity (§38)
	SetVoiceMode(ctx context.Context, in *VoiceModeRequest, opts ...grpc.CallOption) (*VoiceModeResponse, error)
	// Capture the active window as PNG, run OCR, return the extracted text (§42)
	CaptureScreen(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error)
	// Return the current foreground window title and its inferred context tag (§43)
	GetActiveWindow(ctx context.Context, in *WindowRequest, opts ...grpc.CallOption) (*WindowResponse, error)
}

type orchestratorToVoiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorToVoiceClient(cc grpc.ClientConnInterface) OrchestratorToVoiceClient {
	return &orchestratorToVoiceClient{cc}
}

func (c *orchestratorToVoiceClient) SynthesizeSentence(ctx context.Context, in *SynthRequest, opts ...grpc.CallOption) (*SynthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthResponse)
	err := c.cc.Invoke(ctx, OrchestratorToVoice_SynthesizeSentence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToVoiceClient) StreamWakeWord(ctx context.Context, in *WakeWordStartReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WakeWordEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorToVoice_ServiceDesc.Streams[0], OrchestratorToVoice_StreamWakeWord_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WakeWordStartReq, WakeWordEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorToVoice_StreamWakeWordClient = grpc.ServerStreamingClient[WakeWordEvent]

func (c *orchestratorToVoiceClient) SetVoiceMode(ctx context.Context, in *VoiceModeRequest, opts ...grpc.CallOption) (*VoiceModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoiceModeResponse)
	err := c.cc.Invoke(ctx, OrchestratorToVoice_SetVoiceMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToVoiceClient) CaptureScreen(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureResponse)
	err := c.cc.Invoke(ctx, OrchestratorToVoice_CaptureScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToVoiceClient) GetActiveWindow(ctx context.Context, in *WindowRequest, opts ...grpc.CallOption) (*WindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WindowResponse)
	err := c.cc.Invoke(ctx, OrchestratorToVoice_GetActiveWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorToVoiceServer is the server API for OrchestratorToVoice service.
// All implementations must embed UnimplementedOrchestratorToVoiceServer
// for forward compatibility.
type OrchestratorToVoiceServer interface {
	// Send one sentence of text — receive WAV bytes for immediate audio playback (§37 Piper TTS)
	// Called once per sentence as Rust detects sentence boundaries in the token stream
	SynthesizeSentence(context.Context, *SynthRequest) (*SynthResponse, error)
	// Rust opens this stream at startup — Python pushes an event each time wake word is detected (§36)
	StreamWakeWord(*WakeWordStartReq, grpc.ServerStreamingServer[WakeWordEvent]) error
	// Notify voice service of mode change so it can adjust TTS style and VAD sensitivity (§38)
	SetVoiceMode(context.Context, *VoiceModeRequest) (*VoiceModeResponse, error)
	// Capture the active window as PNG, run OCR, return the extracted text (§42)
	CaptureScreen(context.Context, *CaptureRequest) (*CaptureResponse, error)
	// Return the current foreground window title and its inferred context tag (§43)
	GetActiveWindow(context.Context, *WindowRequest) (*WindowResponse, error)
	mustEmbedUnimplementedOrchestratorToVoiceServer()
}

// UnimplementedOrchestratorToVoiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorToVoiceServer struct{}

func (UnimplementedOrchestratorToVoiceServer) SynthesizeSentence(context.Context, *SynthRequest) (*SynthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SynthesizeSentence not implemented")
}
func (UnimplementedOrchestratorToVoiceServer) StreamWakeWord(*WakeWordStartReq, grpc.ServerStreamingServer[WakeWordEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamWakeWord not implemented")
}
func (UnimplementedOrchestratorToVoiceServer) SetVoiceMode(context.Context, *VoiceModeRequest) (*VoiceModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVoiceMode not implemented")
}
func (UnimplementedOrchestratorToVoiceServer) CaptureScreen(context.Context, *CaptureRequest) (*CaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureScreen not implemented")
}
func (UnimplementedOrchestratorToVoiceServer) GetActiveWindow(context.Context, *WindowRequest) (*WindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveWindow not implemented")
}
func (UnimplementedOrchestratorToVoiceServer) mustEmbedUnimplementedOrchestratorToVoiceServer() {}
func (UnimplementedOrchestratorToVoiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorToVoiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorToVoiceServer will
// result in compilation errors.
type UnsafeOrchestratorToVoiceServer interface {
	mustEmbedUnimplementedOrchestratorToVoiceServer()
}

func RegisterOrchestratorToVoiceServer(s grpc.ServiceRegistrar, srv OrchestratorToVoiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorToVoiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorToVoice_ServiceDesc, srv)
}

func _OrchestratorToVoice_SynthesizeSentence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToVoiceServer).SynthesizeSentence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToVoice_SynthesizeSentence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToVoiceServer).SynthesizeSentence(ctx, req.(*SynthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToVoice_StreamWakeWord_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WakeWordStartReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorToVoiceServer).StreamWakeWord(m, &grpc.GenericServerStream[WakeWordStartReq, WakeWordEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorToVoice_StreamWakeWordServer = grpc.ServerStreamingServer[WakeWordEvent]

func _OrchestratorToVoice_SetVoiceMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToVoiceServer).SetVoiceMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToVoice_SetVoiceMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToVoiceServer).SetVoiceMode(ctx, req.(*VoiceModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToVoice_CaptureScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToVoiceServer).CaptureScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToVoice_CaptureScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToVoiceServer).CaptureScreen(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToVoice_GetActiveWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToVoiceServer).GetActiveWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToVoice_GetActiveWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToVoiceServer).GetActiveWindow(ctx, req.(*WindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorToVoice_ServiceDesc is the grpc.ServiceDesc for OrchestratorToVoice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorToVoice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tempest.OrchestratorToVoice",
	HandlerType: (*OrchestratorToVoiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SynthesizeSentence",
			Handler:    _OrchestratorToVoice_SynthesizeSentence_Handler,
		},
		{
			MethodName: "SetVoiceMode",
			Handler:    _OrchestratorToVoice_SetVoiceMode_Handler,
		},
		{
			MethodName: "CaptureScreen",
			Handler:    _OrchestratorToVoice_CaptureScreen_Handler,
		},
		{
			MethodName: "GetActiveWindow",
			Handler:    _OrchestratorToVoice_GetActiveWindow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWakeWord",
			Handler:       _OrchestratorToVoice_StreamWakeWord_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tempest.proto",
}

const (
	OrchestratorToTools_SearchKnowledge_FullMethodName   = "/tempest.OrchestratorToTools/SearchKnowledge"
	OrchestratorToTools_SaveToKnowledge_FullMethodName   = "/tempest.OrchestratorToTools/SaveToKnowledge"
	OrchestratorToTools_BrowseWeb_FullMethodName         = "/tempest.OrchestratorToTools/BrowseWeb"
	OrchestratorToTools_DeepBrowse_FullMethodName        = "/tempest.OrchestratorToTools/DeepBrowse"
	OrchestratorToTools_TakeScreenshot_FullMethodName    = "/tempest.OrchestratorToTools/TakeScreenshot"
	OrchestratorToTools_ReadScreen_FullMethodName        = "/tempest.OrchestratorToTools/ReadScreen"
	OrchestratorToTools_CallClaude_FullMethodName        = "/tempest.OrchestratorToTools/CallClaude"
	OrchestratorToTools_GenerateFlashcard_FullMethodName = "/tempest.OrchestratorToTools/GenerateFlashcard"
	OrchestratorToTools_GenerateDiagram_FullMethodName   = "/tempest.OrchestratorToTools/GenerateDiagram"
	OrchestratorToTools_GenerateMindMap_FullMethodName   = "/tempest.OrchestratorToTools/GenerateMindMap"
	OrchestratorToTools_GenerateReport_FullMethodName    = "/tempest.OrchestratorToTools/GenerateReport"
	OrchestratorToTools_CreateQuiz_FullMethodName        = "/tempest.OrchestratorToTools/CreateQuiz"
	OrchestratorToTools_RunCalculation_FullMethodName    = "/tempest.OrchestratorToTools/RunCalculation"
	OrchestratorToTools_ReadFile_FullMethodName          = "/tempest.OrchestratorToTools/ReadFile"
	OrchestratorToTools_TriggerAutoFill_FullMethodName   = "/tempest.OrchestratorToTools/TriggerAutoFill"
)

// OrchestratorToToolsClient is the client API for OrchestratorToTools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorToToolsClient interface {
	// Search FAISS + knowledge graph for relevant chunks (§16, §19 re-ranking)
	SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeRes, error)
	// Save new content to the knowledge ingestion pipeline (§51, §58)
	SaveToKnowledge(ctx context.Context, in *SaveKnowledgeReq, opts ...grpc.CallOption) (*SaveKnowledgeRes, error)
	// Simple HTTP GET via whitelist fetcher (§40) — returns page text
	BrowseWeb(ctx context.Context, in *BrowseWebReq, opts ...grpc.CallOption) (*BrowseWebRes, error)
	// Full Playwright browser action — click, fill, extract, screenshot (§41)
	DeepBrowse(ctx context.Context, in *DeepBrowseReq, opts ...grpc.CallOption) (*DeepBrowseRes, error)
	// Capture screenshot — delegates to Voice service CaptureScreen (§42)
	TakeScreenshot(ctx context.Context, in *ScreenshotReq, opts ...grpc.CallOption) (*ScreenshotRes, error)
	// Capture screen and return OCR text as a tool result (§42)
	ReadScreen(ctx context.Context, in *ReadScreenReq, opts ...grpc.CallOption) (*ReadScreenRes, error)
	// Call Claude API with a structured prompt template (§50)
	// Used by: gap fill (§49), research agent (§47), training data gen (§68)
	CallClaude(ctx context.Context, in *CallClaudeReq, opts ...grpc.CallOption) (*CallClaudeRes, error)
	// Generate PNG flashcard images via Pillow (§52)
	GenerateFlashcard(ctx context.Context, in *FlashcardReq, opts ...grpc.CallOption) (*FlashcardRes, error)
	// Render Mermaid diagram to PNG via Mermaid CLI (§53)
	GenerateDiagram(ctx context.Context, in *DiagramReq, opts ...grpc.CallOption) (*DiagramRes, error)
	// Build interactive mind map HTML + static PNG from knowledge graph (§54)
	GenerateMindMap(ctx context.Context, in *MindMapReq, opts ...grpc.CallOption) (*MindMapRes, error)
	// Generate PDF/HTML study report via reportlab + matplotlib (§55)
	GenerateReport(ctx context.Context, in *ReportReq, opts ...grpc.CallOption) (*ReportRes, error)
	// Generate MCQ quiz questions with per-option explanations (§62)
	CreateQuiz(ctx context.Context, in *QuizReq, opts ...grpc.CallOption) (*QuizRes, error)
	// Evaluate a mathematical or logical expression (§44)
	RunCalculation(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error)
	// Read a file — restricted to output\ and incoming\ only (§75 permission system)
	ReadFile(ctx context.Context, in *ReadFileReq, opts ...grpc.CallOption) (*ReadFileRes, error)
	// Trigger the auto-fill pipeline for a specific topic (§58)
	TriggerAutoFill(ctx context.Context, in *AutoFillReq, opts ...grpc.CallOption) (*AutoFillRes, error)
}

type orchestratorToToolsClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorToToolsClient(cc grpc.ClientConnInterface) OrchestratorToToolsClient {
	return &orchestratorToToolsClient{cc}
}

func (c *orchestratorToToolsClient) SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKnowledgeRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_SearchKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) SaveToKnowledge(ctx context.Context, in *SaveKnowledgeReq, opts ...grpc.CallOption) (*SaveKnowledgeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveKnowledgeRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_SaveToKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) BrowseWeb(ctx context.Context, in *BrowseWebReq, opts ...grpc.CallOption) (*BrowseWebRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowseWebRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_BrowseWeb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) DeepBrowse(ctx context.Context, in *DeepBrowseReq, opts ...grpc.CallOption) (*DeepBrowseRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeepBrowseRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_DeepBrowse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) TakeScreenshot(ctx context.Context, in *ScreenshotReq, opts ...grpc.CallOption) (*ScreenshotRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenshotRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_TakeScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) ReadScreen(ctx context.Context, in *ReadScreenReq, opts ...grpc.CallOption) (*ReadScreenRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadScreenRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_ReadScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) CallClaude(ctx context.Context, in *CallClaudeReq, opts ...grpc.CallOption) (*CallClaudeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallClaudeRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_CallClaude_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) GenerateFlashcard(ctx context.Context, in *FlashcardReq, opts ...grpc.CallOption) (*FlashcardRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlashcardRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_GenerateFlashcard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) GenerateDiagram(ctx context.Context, in *DiagramReq, opts ...grpc.CallOption) (*DiagramRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagramRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_GenerateDiagram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) GenerateMindMap(ctx context.Context, in *MindMapReq, opts ...grpc.CallOption) (*MindMapRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MindMapRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_GenerateMindMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) GenerateReport(ctx context.Context, in *ReportReq, opts ...grpc.CallOption) (*ReportRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_GenerateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) CreateQuiz(ctx context.Context, in *QuizReq, opts ...grpc.CallOption) (*QuizRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuizRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_CreateQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) RunCalculation(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalcRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_RunCalculation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) ReadFile(ctx context.Context, in *ReadFileReq, opts ...grpc.CallOption) (*ReadFileRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorToToolsClient) TriggerAutoFill(ctx context.Context, in *AutoFillReq, opts ...grpc.CallOption) (*AutoFillRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoFillRes)
	err := c.cc.Invoke(ctx, OrchestratorToTools_TriggerAutoFill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorToToolsServer is the server API for OrchestratorToTools service.
// All implementations must embed UnimplementedOrchestratorToToolsServer
// for forward compatibility.
type OrchestratorToToolsServer interface {
	// Search FAISS + knowledge graph for relevant chunks (§16, §19 re-ranking)
	SearchKnowledge(context.Context, *SearchKnowledgeReq) (*SearchKnowledgeRes, error)
	// Save new content to the knowledge ingestion pipeline (§51, §58)
	SaveToKnowledge(context.Context, *SaveKnowledgeReq) (*SaveKnowledgeRes, error)
	// Simple HTTP GET via whitelist fetcher (§40) — returns page text
	BrowseWeb(context.Context, *BrowseWebReq) (*BrowseWebRes, error)
	// Full Playwright browser action — click, fill, extract, screenshot (§41)
	DeepBrowse(context.Context, *DeepBrowseReq) (*DeepBrowseRes, error)
	// Capture screenshot — delegates to Voice service CaptureScreen (§42)
	TakeScreenshot(context.Context, *ScreenshotReq) (*ScreenshotRes, error)
	// Capture screen and return OCR text as a tool result (§42)
	ReadScreen(context.Context, *ReadScreenReq) (*ReadScreenRes, error)
	// Call Claude API with a structured prompt template (§50)
	// Used by: gap fill (§49), research agent (§47), training data gen (§68)
	CallClaude(context.Context, *CallClaudeReq) (*CallClaudeRes, error)
	// Generate PNG flashcard images via Pillow (§52)
	GenerateFlashcard(context.Context, *FlashcardReq) (*FlashcardRes, error)
	// Render Mermaid diagram to PNG via Mermaid CLI (§53)
	GenerateDiagram(context.Context, *DiagramReq) (*DiagramRes, error)
	// Build interactive mind map HTML + static PNG from knowledge graph (§54)
	GenerateMindMap(context.Context, *MindMapReq) (*MindMapRes, error)
	// Generate PDF/HTML study report via reportlab + matplotlib (§55)
	GenerateReport(context.Context, *ReportReq) (*ReportRes, error)
	// Generate MCQ quiz questions with per-option explanations (§62)
	CreateQuiz(context.Context, *QuizReq) (*QuizRes, error)
	// Evaluate a mathematical or logical expression (§44)
	RunCalculation(context.Context, *CalcReq) (*CalcRes, error)
	// Read a file — restricted to output\ and incoming\ only (§75 permission system)
	ReadFile(context.Context, *ReadFileReq) (*ReadFileRes, error)
	// Trigger the auto-fill pipeline for a specific topic (§58)
	TriggerAutoFill(context.Context, *AutoFillReq) (*AutoFillRes, error)
	mustEmbedUnimplementedOrchestratorToToolsServer()
}

// UnimplementedOrchestratorToToolsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorToToolsServer struct{}

func (UnimplementedOrchestratorToToolsServer) SearchKnowledge(context.Context, *SearchKnowledgeReq) (*SearchKnowledgeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchKnowledge not implemented")
}
func (UnimplementedOrchestratorToToolsServer) SaveToKnowledge(context.Context, *SaveKnowledgeReq) (*SaveKnowledgeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveToKnowledge not implemented")
}
func (UnimplementedOrchestratorToToolsServer) BrowseWeb(context.Context, *BrowseWebReq) (*BrowseWebRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BrowseWeb not implemented")
}
func (UnimplementedOrchestratorToToolsServer) DeepBrowse(context.Context, *DeepBrowseReq) (*DeepBrowseRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeepBrowse not implemented")
}
func (UnimplementedOrchestratorToToolsServer) TakeScreenshot(context.Context, *ScreenshotReq) (*ScreenshotRes, error) {
	return nil, status.Error(codes.Unimplemented, "method TakeScreenshot not implemented")
}
func (UnimplementedOrchestratorToToolsServer) ReadScreen(context.Context, *ReadScreenReq) (*ReadScreenRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadScreen not implemented")
}
func (UnimplementedOrchestratorToToolsServer) CallClaude(context.Context, *CallClaudeReq) (*CallClaudeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CallClaude not implemented")
}
func (UnimplementedOrchestratorToToolsServer) GenerateFlashcard(context.Context, *FlashcardReq) (*FlashcardRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateFlashcard not implemented")
}
func (UnimplementedOrchestratorToToolsServer) GenerateDiagram(context.Context, *DiagramReq) (*DiagramRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDiagram not implemented")
}
func (UnimplementedOrchestratorToToolsServer) GenerateMindMap(context.Context, *MindMapReq) (*MindMapRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateMindMap not implemented")
}
func (UnimplementedOrchestratorToToolsServer) GenerateReport(context.Context, *ReportReq) (*ReportRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedOrchestratorToToolsServer) CreateQuiz(context.Context, *QuizReq) (*QuizRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuiz not implemented")
}
func (UnimplementedOrchestratorToToolsServer) RunCalculation(context.Context, *CalcReq) (*CalcRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCalculation not implemented")
}
func (UnimplementedOrchestratorToToolsServer) ReadFile(context.Context, *ReadFileReq) (*ReadFileRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedOrchestratorToToolsServer) TriggerAutoFill(context.Context, *AutoFillReq) (*AutoFillRes, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerAutoFill not implemented")
}
func (UnimplementedOrchestratorToToolsServer) mustEmbedUnimplementedOrchestratorToToolsServer() {}
func (UnimplementedOrchestratorToToolsServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorToToolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorToToolsServer will
// result in compilation errors.
type UnsafeOrchestratorToToolsServer interface {
	mustEmbedUnimplementedOrchestratorToToolsServer()
}

func RegisterOrchestratorToToolsServer(s grpc.ServiceRegistrar, srv OrchestratorToToolsServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorToToolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorToTools_ServiceDesc, srv)
}

func _OrchestratorToTools_SearchKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKnowledgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).SearchKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_SearchKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).SearchKnowledge(ctx, req.(*SearchKnowledgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_SaveToKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveKnowledgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).SaveToKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_SaveToKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).SaveToKnowledge(ctx, req.(*SaveKnowledgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_BrowseWeb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseWebReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).BrowseWeb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_BrowseWeb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).BrowseWeb(ctx, req.(*BrowseWebReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_DeepBrowse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeepBrowseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).DeepBrowse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_DeepBrowse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).DeepBrowse(ctx, req.(*DeepBrowseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_TakeScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).TakeScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_TakeScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).TakeScreenshot(ctx, req.(*ScreenshotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_ReadScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadScreenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).ReadScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_ReadScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).ReadScreen(ctx, req.(*ReadScreenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_CallClaude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallClaudeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).CallClaude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_CallClaude_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).CallClaude(ctx, req.(*CallClaudeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_GenerateFlashcard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashcardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).GenerateFlashcard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_GenerateFlashcard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).GenerateFlashcard(ctx, req.(*FlashcardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_GenerateDiagram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagramReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).GenerateDiagram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_GenerateDiagram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).GenerateDiagram(ctx, req.(*DiagramReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_GenerateMindMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MindMapReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).GenerateMindMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_GenerateMindMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).GenerateMindMap(ctx, req.(*MindMapReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_GenerateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).GenerateReport(ctx, req.(*ReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_CreateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuizReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).CreateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_CreateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).CreateQuiz(ctx, req.(*QuizReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_RunCalculation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).RunCalculation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_RunCalculation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).RunCalculation(ctx, req.(*CalcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).ReadFile(ctx, req.(*ReadFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorToTools_TriggerAutoFill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoFillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorToToolsServer).TriggerAutoFill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorToTools_TriggerAutoFill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorToToolsServer).TriggerAutoFill(ctx, req.(*AutoFillReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorToTools_ServiceDesc is the grpc.ServiceDesc for OrchestratorToTools service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorToTools_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tempest.OrchestratorToTools",
	HandlerType: (*OrchestratorToToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchKnowledge",
			Handler:    _OrchestratorToTools_SearchKnowledge_Handler,
		},
		{
			MethodName: "SaveToKnowledge",
			Handler:    _OrchestratorToTools_SaveToKnowledge_Handler,
		},
		{
			MethodName: "BrowseWeb",
			Handler:    _OrchestratorToTools_BrowseWeb_Handler,
		},
		{
			MethodName: "DeepBrowse",
			Handler:    _OrchestratorToTools_DeepBrowse_Handler,
		},
		{
			MethodName: "TakeScreenshot",
			Handler:    _OrchestratorToTools_TakeScreenshot_Handler,
		},
		{
			MethodName: "ReadScreen",
			Handler:    _OrchestratorToTools_ReadScreen_Handler,
		},
		{
			MethodName: "CallClaude",
			Handler:    _OrchestratorToTools_CallClaude_Handler,
		},
		{
			MethodName: "GenerateFlashcard",
			Handler:    _OrchestratorToTools_GenerateFlashcard_Handler,
		},
		{
			MethodName: "GenerateDiagram",
			Handler:    _OrchestratorToTools_GenerateDiagram_Handler,
		},
		{
			MethodName: "GenerateMindMap",
			Handler:    _OrchestratorToTools_GenerateMindMap_Handler,
		},
		{
			MethodName: "GenerateReport",
			Handler:    _OrchestratorToTools_GenerateReport_Handler,
		},
		{
			MethodName: "CreateQuiz",
			Handler:    _OrchestratorToTools_CreateQuiz_Handler,
		},
		{
			MethodName: "RunCalculation",
			Handler:    _OrchestratorToTools_RunCalculation_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _OrchestratorToTools_ReadFile_Handler,
		},
		{
			MethodName: "TriggerAutoFill",
			Handler:    _OrchestratorToTools_TriggerAutoFill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tempest.proto",
}
